"""device__new_table

Revision ID: 171e2a85fa40
Revises: 
Create Date: 2022-09-19 06:34:38.700746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "171e2a85fa40"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column(
            "create_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "update_date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("firmware_version", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device")
    # ### end Alembic commands ###
